-- TABLE 삭제 및 생성
DROP TABLE MVC_MEMBER;
CREATE TABLE MVC_MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30) UNIQUE,
    MPHOTO VARCHAR2(30),
    MBIRTH DATE,
    MADDRESS VARCHAR2(200),
    MRDATE DATE DEFAULT SYSDATE
);

-- 회원가입
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('aaa', '111', '홍길동', 'hong@hong.com', NULL, '1999-01-01', NULL);
    
-- 아이디 체크
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa';
-- 이메일 체크
SELECT * FROM MVC_MEMBER WHERE MEMAIL LIKE '%'||'hong'||'%';

-- DTO 가져오기
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa';

COMMIT;