-- TABLE 삭제 및 생성
DROP TABLE MVC_FILEBOARD;
DROP SEQUENCE MVC_FILEBOARD_SEQ;
DROP TABLE MVC_MEMBER;
DROP TABLE MVC_ADMIN;

CREATE TABLE MVC_MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30) UNIQUE,
    MPHOTO VARCHAR2(30),
    MBIRTH DATE,
    MADDRESS VARCHAR2(200),
    MRDATE DATE DEFAULT SYSDATE
);

CREATE TABLE MVC_FILEBOARD(
    FID NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MVC_MEMBER (MID),
    FTITLE VARCHAR2(100) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FFILENAME VARCHAR2(100),
    FRDATE DATE DEFAULT SYSDATE,
    FHIT NUMBER(6) DEFAULT 0 NOT NULL,
    FGROUP NUMBER(6) NOT NULL,
    FSTEP NUMBER(6) NOT NULL,
    FINDENT NUMBER(6) NOT NULL,
    FIP VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE MVC_FILEBOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

CREATE TABLE MVC_ADMIN(
    AID VARCHAR2(30) PRIMARY KEY,
    APW VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30) NOT NULL,
    ARDATE DATE DEFAULT SYSDATE
);
-- 정보수정
UPDATE MVC_MEMBER SET MPW = '111', MNAME = '홍길동', MEMAIL = 'hong@hong.com', MPHOTO = 'NOIMG.JPG', MBIRTH = '1999-01-01', MADDRESS = '서울'
    WHERE MID = 'aaa';

-- 회원가입
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('aaa', '111', '홍길동', 'hong@hong.com', NULL, '1999-01-01', NULL);
-- 로그인 체크
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa' AND MPW = '111';
-- 아이디 체크
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa';
-- 이메일 체크
SELECT * FROM MVC_MEMBER WHERE MEMAIL LIKE '%'||'hong'||'%';

-- DTO 가져오기
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa';

-- 회원탈퇴
DELETE FROM MVC_MEMBER WHERE MID = 'aaa';

-- 글 작성
INSERT INTO MVC_FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FHIT, FGROUP, FSTEP, FINDENT, FIP)
    VALUES (MVC_FILEBOARD_SEQ.NEXTVAL, 'aaa', '제목', '내용', NULL, 0, MVC_FILEBOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');

-- 글 목록
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT F.*, MNAME FROM MVC_FILEBOARD F, MVC_MEMBER M
                    WHERE F.MID = M.MID ORDER BY FGROUP DESC, FSTEP) A)
    WHERE RN BETWEEN 1 AND 5;
    
-- 상세보기 / dto 가져오기
SELECT * FROM MVC_FILEBOARD WHERE FID = 1;

-- 글 수정
UPDATE MVC_FILEBOARD SET FTITLE = '수정제목', FCONTENT = '수정내용', FFILENAME = NULL, FIP = '127.0.0.2'
    WHERE FID = 1;

-- 글삭제
DELETE FROM MVC_FILEBOARD WHERE FID = 1;

-- 답변 전 step A
UPDATE MVC_FILEBOARD SET FSTEP = FSTEP + 1 WHERE FGROUP = 3 AND FSTEP > 1;

-- 글 답변
INSERT INTO MVC_FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FHIT, FGROUP, FSTEP, FINDENT, FIP)
    VALUES (MVC_FILEBOARD_SEQ.NEXTVAL, 'aaa', '답변', '답변', NULL, 0, 1, 1, 1, '127.0.0.3');

-- 조회수 올리기
UPDATE MVC_FILEBOARD SET FHIT = FHIT + 1 WHERE FID = 3;
-- 게시글 수
SELECT COUNT(*) CNT FROM MVC_FILEBOARD;

-- 관리자 로그인 체크
SELECT * FROM MVC_ADMIN WHERE AID = 'AAA' AND APW = '111';

-- 관리자 등록
INSERT INTO MVC_ADMIN (AID, APW, ANAME) VALUES ('AAA', '111', '관리자');

-- 관리자 dto 가져오기
SELECT * FROM MVC_ADMIN WHERE AID = 'AAA';

-- 전체 회원 리스트
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM MVC_MEMBER ORDER BY MRDATE DESC) A)
    WHERE RN BETWEEN 1 AND 2;
-- 회원수
SELECT COUNT(*) CNT FROM MVC_MEMBER;
COMMIT;
