DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30),
    MPHOTO VARCHAR2(30),
    MBIRTH DATE NOT NULL,
    MADDRESS VARCHAR2(300),
    MRDATE DATE DEFAULT SYSDATE
);

INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('aaa', '111', '송중기', 'song@song.com', 'song.jpg', '1988-01-01', '서울');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('bbb', '111', '송혜교', 'song2@song.com', 'song2.jpg', '1980-01-01', '서울');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('ccc', '111', '손흥민', 'son@song.com', 'son.jpg', '1990-01-01', '서울');
    
SELECT * FROM MEMBER WHERE MID = 'aaa' AND MPW = '111';

UPDATE MEMBER SET MPW = '222', MNAME = '송중기', MEMAIL = 'SONG@SONG.COM', MBIRTH = '1988-08-08', MADDRESS = '강남'
    WHERE MID = 'aaa';

SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM MEMBER ORDER BY MRDATE DESC) A)
    WHERE RN BETWEEN 1 AND 2;
    
SELECT * FROM MEMBER WHERE MID = 'aaa';

SELECT COUNT(*) CNT FROM MEMBER;

COMMIT;