DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BID         NUMBER(6)       PRIMARY KEY,
    BNAME       VARCHAR2(50)    NOT NULL,
    BTITLE      VARCHAR2(100)   NOT NULL,
    BCONTENT    VARCHAR2(1000),
    BDATE       DATE            DEFAULT SYSDATE NOT NULL,
    BHIT        NUMBER(6)       DEFAULT 0 NOT NULL,
    BGROUP      NUMBER(6)       NOT NULL,
    BSTEP       NUMBER(3)       NOT NULL,
    BINDENT     NUMBER(3)       NOT NULL,
    BIP         VARCHAR2(20)    NOT NULL
);

INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '글제목', '본문', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '김길동', '글제목1', '본문1', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.2');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '서길동', '글제목2', '본문2', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.3');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '소길동', '답변', '답', 1, 1, 1, '127.0.0.1');
    
-- 글 수
SELECT COUNT(*) CNT FROM BOARD;
    
-- 글 목록
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;

SELECT * 
    FROM (SELECT ROWNUM RN,  A.*
        FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 1 AND 3;

-- 글쓰기
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '소길동', '답변', '답', 1, 1, 1, '127.0.0.1');

 -- 글수정
 UPDATE BOARD SET BNAME = '서길동', BTITLE = '수정제목', BCONTENT = '수정 내용', BIP = '127.0.0.4' WHERE BID = 2;
 
 -- 글삭제
 DELETE FROM BOARD WHERE BID = 4;
 
 -- 조회수 올리기
 UPDATE BOARD SET BHIT = BHIT + 1 WHERE BID = 3;
 
 -- 글 상세 보기
 SELECT * FROM BOARD WHERE BID = 3;
 
 -- 답변전 STEP A
 UPDATE BOARD SET BSTEP = BSTEP + 1 WHERE BGROUP  = 3 AND BSTEP > 0;
 
 -- 답변글 작성
 INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '답길동', '답변', '답', 3, 1, 1, '127.0.0.1');
 
 COMMIT;
 