-- [Ⅵ] SUB QUERY : QUERY 안에 QUERY가 내포
-- SELECT 필드1                        * 서브쿼리 = (SELECT 필드 FROM 테이블 WHERE 조건)
--  FROM 테이블
--  WHERE 조건 (서브쿼리)
-- 서브쿼리는 반드시 괄호로 감싸야함

-- 1. 서브쿼리 개념
-- ex. 최고 급여를 받는 사람의 사번, 이름, 직책, 급여

-- 서브쿼리
SELECT MAX(SAL) FROM EMP;

-- 메인쿼리
SELECT EMPNO, ENAME, JOB, SAL
    FROM EMP
    WHERE SAL = (SELECT MAX(SAL) FROM EMP);

-- 서브쿼리의 종류(1) 단일행 서브쿼리(서브쿼리의 결과가 단일행) : =, >, >=, <, <=, !=
-- ex. SCOTT이 근무하는 부서번호 출력
SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';  -- 서브쿼리
SELECT DNAME
    FROM DEPT 
    WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT');  -- 메인쿼리(서브쿼리 사용)

SELECT DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND ENAME = 'SCOTT';  -- JOIN 사용

-- 서브쿼리의 종류(2) 다중행 서브쿼리(서브쿼리 결과가 2행이상) : IN, ANY, ALL, EXISTS
-- ex. JOB이 MANAGER인 사람의 부서이름
SELECT DEPTNO FROM EMP WHERE JOB = 'MANAGER';  -- 서브쿼리
SELECT DNAME 
    FROM DEPT 
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB = 'MANAGER');
    
SELECT DNAME FROM DEPT WHERE DEPTNO IN (10, 20, 30);
    
-- 2. 단일행 서브쿼리
SELECT E.DEPTNO, LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND ENAME = 'SCOTT';
INSERT INTO DEPT VALUES (50, 'IT', 'DALLAS');
INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (9999, '홍길동', 50);

-- ex. SCOTT과 같은 부서인 사람의 이름과 급여 출력
SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';
SELECT ENAME, SAL FROM EMP 
    WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT') 
    AND ENAME != 'SCOTT';
    
-- ex. SCOTT과 같은 근무지인 사람의 이름과 급여 출력 
SELECT LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND ENAME = 'SCOTT';
SELECT ENAME, SAL FROM EMP E, DEPT D 
    WHERE E.DEPTNO = D.DEPTNO
    AND LOC = (SELECT LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND ENAME = 'SCOTT')
    AND ENAME != 'SCOTT';

-- ex. 최초입사일과 최초입사한 사람의 이름, 최근입사일과 최근입사한 사람의 이름
-- 1단계
SELECT MIN(HIREDATE) FROM EMP;
SELECT HIREDATE, ENAME FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP);
-- 2단계
SELECT MAX(HIREDATE) FROM EMP;
SELECT HIREDATE, ENAME FROM EMP WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP);
-- 3단계
SELECT E1.HIREDATE FIRST, E1.ENAME FIRSTMAN, E2.HIREDATE LAST, E2.ENAME LASTMAN
    FROM EMP E1, EMP E2
    WHERE E1.HIREDATE = (SELECT MIN(HIREDATE) FROM EMP)
    AND E2.HIREDATE = (SELECT MAX(HIREDATE) FROM EMP);
-- 다른답
SELECT (SELECT MIN(HIREDATE) FROM EMP),
       (SELECT ENAME FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP)),
       (SELECT MAX(HIREDATE) FROM EMP),
       (SELECT ENAME FROM EMP WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP))
    FROM DUAL;

-- ex. SCOTT과 같은 부서에 근무하는 사람들의 급여합
SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';
SELECT SUM(SAL) FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT');

-- ex. SCOTT과 동일한 직책(JOB)을 가진 사원의 모든 필드
SELECT JOB FROM EMP WHERE ENAME = 'SCOTT';
SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SCOTT');

-- ex. 'KING'이 직속상사인 사원의 이름과 급여
SELECT EMPNO FROM EMP WHERE ENAME = 'KING';
SELECT ENAME, SAL FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');

SELECT W.ENAME, W.SAL
    FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO
    AND M.ENAME = 'KING';
    
-- ex. 평균 급여 이하로 받는 사원의 이름과 급여 출력
SELECT AVG(SAL) FROM EMP;
SELECT ENAME, SAL FROM EMP WHERE SAL <= (SELECT AVG(SAL) FROM EMP);















