SELECT * FROM USER_TABLES; -- SCOTT2 가 가지고 있는 테이블
SELECT * FROM ALL_TABLES; -- SCOTT2 가 접근 가능한 테이블
SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT', 'EMP');
SHOW USER;
SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO = D.DEPTNO;
EXIT;