-- [Ⅶ] DDL, DCL, DML
-- DDL
-- 1. 테이블 생성(CREATE TABLE)
CREATE TABLE BOOK(
    BOOKID NUMBER(4),
    BOOKNAME VARCHAR2(300),
    PUBLISHER VARCHAR2(300),
    RDATE DATE,
    PRICE NUMBER(8),
    PRIMARY KEY(BOOKID));
    
DESC BOOK;


