-- [Ⅷ] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;

SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND (
    NUM NUMBER(4),  -- 시퀀스 사용
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(30) UNIQUE,
    ADDRESS VARCHAR2(300),
    LAST_MODIFYED DATE DEFAULT SYSDATE,
    PRIMARY KEY (NUM) );
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 용산구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999', '서울시 강남구 강남대로 94길 13 삼겸빌당 402');
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-8888', '서울시 영등포구');
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;  -- 현재 시퀀스 값
COMMIT;

-- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 test_seq 시퀀스 생성
DROP SEQUENCE TEST_SEQ;
CREATE SEQUENCE TEST_SEQ
    START WITH 101
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 시퀀스를 실행하지 않앗 값이 없어서 에러
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
    
    
    
    
    
    