-- [11] INDEX  : 조회를 빠르게 하는 인덱스
SELECT * FROM USER_INDEXES;  -- 딕셔너리뷰에서 SCOTT이 소유한 인덱스 정보
DESC EMP;
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT COUNT(*) FROM EMP01;
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (1111, 'HONG');
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT TO_CHAR(COUNT(*), '9,999,999') FROM EMP01;

SELECT * FROM EMP01 WHERE ENAME = 'HONG';
CREATE INDEX IDX_EMP_ENAME ON EMP01(ENAME);
SELECT * FROM EMP01 WHERE ENAME = 'HONG';
INSERT INTO EMP01 SELECT * FROM EMP01;
DROP INDEX IDX_EMP_ENAME;
INSERT INTO EMP01 SELECT * FROM EMP01;