-- 연습문제 5.
CREATE TABLE MAJOR (
    MAJOR_CODE          NUMBER(2),
    MAJOR_NAME          VARCHAR2(30) UNIQUE,
    MAJOR_OFFICE_LOC    VARCHAR2(60) NOT NULL,
    PRIMARY KEY(MAJOR_CODE) );
    
INSERT INTO MAJOR VALUES (1, '경영정보', '경영관 305호');
INSERT INTO MAJOR VALUES (2, '소프트웨어공학', '정보관 808호');
INSERT INTO MAJOR VALUES (3, '디자인', '예술관 606호');
INSERT INTO MAJOR VALUES (4, '경제', '경상관 202호');

CREATE TABLE STUDENT (
    STUDENT_CODE         VARCHAR2(5),
    STUDENT_NAME         VARCHAR2(30) NOT NULL,
    SCORE                NUMBER(3),
    MAJOR_CODE           NUMBER(2),
    PRIMARY KEY (STUDENT_CODE),
    CHECK ((SCORE BETWEEN 0 AND 100) AND SCORE != 0),
    FOREIGN KEY (MAJOR_CODE) REFERENCES MAJOR (MAJOR_CODE) );
    
INSERT INTO STUDENT VALUES ('A01', '김길동', 100, 1);
INSERT INTO STUDENT VALUES ('A02', '문길동', 90, 2);
INSERT INTO STUDENT VALUES ('A03', '홍길동', 95, 1);

COMMIT;

SELECT * FROM MAJOR;
SELECT * FROM STUDENT;