-- 연습문제 4.
CREATE TABLE BOOKCATEGORY (
    CATEGORY_CODE       NUMBER(3),
    CATEGORY_NAME       VARCHAR2(50) UNIQUE,
    OFFICE_LOC          VARCHAR2(50) NOT NULL,
    PRIMARY KEY (CATEGORY_CODE) );
    
INSERT INTO BOOKCATEGORY VALUES (100, '철학', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (200, '인문', '3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (300, '자연과학', '4층 과학실');
INSERT INTO BOOKCATEGORY VALUES (400, 'IT', '4층 과학실');
    
CREATE TABLE BOOK (
    BOOKNO          VARCHAR2(10),
    CATEGORY_CODE   NUMBER(3),
    BOOKNAME        VARCHAR2(50),
    PUBLISHER       VARCHAR2(50),
    PUBYEAR         NUMBER(4) DEFAULT EXTRACT(YEAR FROM SYSDATE),
    PRIMARY KEY (BOOKNO),
    FOREIGN KEY (CATEGORY_CODE) REFERENCES BOOKCATEGORY (CATEGORY_CODE) );

INSERT INTO BOOK (BOOKNO, CATEGORY_CODE, BOOKNAME, PUBLISHER)
    VALUES ('100A01', 100, '철학자의 삶', '더존출판');
INSERT INTO BOOK (BOOKNO, CATEGORY_CODE, BOOKNAME, PUBLISHER)
    VALUES ('400A01', 400, '이것이 DB다', '더존출판');

COMMIT;

SELECT * FROM BOOKCATEGORY;
SELECT * FROM BOOK;