-- ÃÑ ¿¬½À¹®Á¦ 1.
CREATE TABLE MEMBER_LEVEL (
    LEVELNO         NUMBER(1),
    LEVELNAME       VARCHAR2(10) NOT NULL,
    PRIMARY KEY (LEVELNO) );

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, 'ÀÏ¹Ý');
INSERT INTO MEMBER_LEVEL VALUES (1, '½Ç¹ö');
INSERT INTO MEMBER_LEVEL VALUES (2, '°ñµå');

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE MEMBER (
    MNO         NUMBER(3),
    MNAME       VARCHAR2(30) NOT NULL,
    MPW         VARCHAR2(8) NOT NULL,
    MMAIL       VARCHAR2(20) UNIQUE,
    MPOINT      NUMBER(6),
    MRDATE      DATE DEFAULT SYSDATE,
    LEVELNO     NUMBER(1),
    PRIMARY KEY (MNO),
    CHECK (LENGTH(MPW) <= 8),
    CHECK (MPOINT >= 0),
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL (LEVELNO) );
    
INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'È«±æµ¿', 'aa', 'hong@hong.com', 0, '22/03/10', 0);
INSERT INTO MEMBER (MNO, MNAME, MPW, MMAIL, MPOINT, LEVELNO)
    VALUES (MEMBER_SEQ.NEXTVAL, '½Å±æµ¿', 'bb', 'sin@sin.com', 1000, 1);

COMMIT;

SELECT * FROM MEMBER_LEVEL;
SELECT * FROM MEMBER;

SELECT MNO, MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') "mRDATE", MMAIL, MPOINT, LEVELNAME||'°í°´' "levelname"
    FROM MEMBER M, MEMBER_LEVEL ML
    WHERE M.LEVELNO = ML.LEVELNO;