CREATE TABLE MY_DATA (
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10, 2) );
    
INSERT INTO MY_DATA VALUES (1, 'SCOTT', 'SSCOTT', 10000);
INSERT INTO MY_DATA VALUES (2, 'FORD', 'FFORD', 13000);
INSERT INTO MY_DATA VALUES (3, 'PATEL', 'PPATEL', 33000);
INSERT INTO MY_DATA VALUES (4, 'REPORT', 'RREPORT', 23500);
INSERT INTO MY_DATA VALUES (5, 'GOOD', 'GGOOD', 44450);

SELECT * FROM MY_DATA;
SELECT ID, INITCAP(NAME) NAME, LOWER(USERID) USERID, TO_CHAR(SALARY, '99,999.99') SALARY FROM MY_DATA;
COMMIT;
UPDATE MY_DATA SET SALARY = 65000.00 WHERE ID = 3;
COMMIT;
DELETE FROM MY_DATA WHERE NAME = 'FORD';
COMMIT;
UPDATE MY_DATA SET SAL = 15000.00 WHERE SAL <= 15000;
DROP TABLE MY_DATA;