-- 연습문제

--	1. Comm이 null이 아닌 사원의 이름, 급여, 등급, 부서번호, 부서이름, 근무지를 출력하시오.
SELECT ENAME, SAL, GRADE, D.DEPTNO, DNAME, LOC
    FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND NOT COMM IS NULL AND SAL BETWEEN LOSAL AND HISAL;

--	2. 이름, 급여, 입사일, 급여등급
SELECT ENAME, SAL, HIREDATE, GRADE
    FROM EMP E, SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL;

--	3. 이름, 급여, 입사일, 급여등급, 부서명, 근무지
SELECT ENAME, SAL, HIREDATE, GRADE, DNAME, LOC
    FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL;

--	4. 이름, 급여, 등급, 부서코드, 근무지. 단 comm 이 null아닌 경우
SELECT ENAME, SAL, GRADE, D.DEPTNO, LOC
    FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND NOT COMM IS NULL;

--	5. 이름, 급여, 급여등급, 연봉, 부서명, (부서별 출력, 부서가 같으면 연봉순. 연봉=(sal+comm)*12 comm이 null이면 0)
SELECT ENAME, SAL, GRADE, (SAL+NVL(COMM, 0))*12 ANNALY_SAL, DNAME
    FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL
    ORDER BY DNAME, ANNALY_SAL; 

--	6. 이름, 업무, 급여, 등급, 부서코드, 부서명 출력. 급여가 1000~3000사이. 정렬조건 : 부서별, 부서같으면 업무별, 업무같으면 급여 큰순
SELECT ENAME, JOB, SAL, GRADE, D.DEPTNO, DNAME
    FROM EMP E, SALGRADE, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL
    AND SAL BETWEEN 1000 AND 3000
    ORDER BY DNAME, JOB, SAL;

--	7. 이름, 급여, 등급, 입사일, 근무지. 81년에 입사한 사람. 등급 큰순
SELECT ENAME, SAL, GRADE, HIREDATE, LOC
    FROM EMP E, DEPT D, SALGRADE
    WHERE E.DEPTNO = D.DEPTNO AND HIREDATE LIKE '81%' AND SAL BETWEEN LOSAL AND HISAL
    ORDER BY GRADE;
    
-- 8. SCOTT과 동일한 부서번호(20)에서 근무하는 사원의 이름을 출력하시오
-- 1단계
SELECT * FROM EMP WHERE ENAME = 'SCOTT';
SELECT ENAME FROM EMP WHERE DEPTNO = 20 AND ENAME != 'SCOTT';

-- 2단계
SELECT E2.ENAME FROM EMP E1, EMP E2
    WHERE E1.ENAME = 'SCOTT' AND E1.DEPTNO = E2.DEPTNO AND E2.ENAME != 'SCOTT';


    
-- 9. SCOTT과 동일한 근무지(DALLAS)에서 근무하는 사원의 이름을 출력하시오(2단계 최종문제)
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES (50, 'IT', 'DALLAS');  -- 인위적으로 DALLAS 근무지 부서 하나 추가
INSERT INTO EMP VALUES (9999, '홍길동', NULL, NULL, NULL, 9000, 900, 50);  -- 인위적으로 50번 부서 사원 추가
SELECT * FROM EMP;

-- 1단계
SELECT ENAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO
    AND LOC = 'DALLAS' AND ENAME != 'SCOTT';
 
-- 2단계   
SELECT E2.ENAME FROM EMP E1, EMP E2, DEPT D1, DEPT D2
    WHERE E1.ENAME = 'SCOTT' AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO 
    AND D1.LOC = D2.LOC AND E2.ENAME != 'SCOTT';
    
-- 10. 상사의 이름이 'KING'인 사원들의 이름과 업무를 출력
SELECT W.ENAME, W.JOB
    FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO AND M.ENAME = 'KING';
    