CREATE SEQUENCE MK_SEQ
    START WITH 00001
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE MK (
    MNO         NUMBER(12),
    MNAME       VARCHAR2(30) NOT NULL,
    MPW         VARCHAR2(8) NOT NULL,
    MMAIL       VARCHAR2(20) UNIQUE,
    MPOINT      NUMBER(6),
    MRDATE      DATE DEFAULT SYSDATE,
    LEVELNO     NUMBER(1),
    PRIMARY KEY (MNO),
    CHECK (LENGTH(MPW) <= 8),
    CHECK (MPOINT >= 0)
    );
    
SELECT * FROM MK;
DROP TABLE MK;
DROP SEQUENCE MK_SEQ;

INSERT INTO MK VALUES (MK_SEQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '22/03/10', 0);
INSERT INTO MK (MNO, MNAME, MPW, MMAIL, MPOINT, LEVELNO)
    VALUES (MK_SEQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, 1);

COMMIT;

SELECT TO_CHAR(SYSDATE, 'RRMMDD')||TO_CHAR(MNO, '00000') "주문번호", MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') "mRDATE", MMAIL, MPOINT
    FROM MK;