--
SELECT * FROM DEPT WHERE DEPTNO = 70;
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO = 70;

INSERT INTO DEPT VALUES (70, 'IT', 'SEOUL');
SELECT * FROM DEPT;
DELETE FROM DEPT WHERE DEPTNO = 50;
ROLLBACK;
COMMIT;

UPDATE DEPT SET DNAME = 'ABC', LOC = 'SEOUL' WHERE DEPTNO = 10;
