DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
    PHONE VARCHAR2(13),
    NAME VARCHAR(15) NOT NULL,
    POINT NUMBER(7) DEFAULT 0,
    PRIMARY KEY(PHONE),
    CHECK (POINT >= 0) );

-- 가입 
INSERT INTO CUSTOMER VALUES ('010-9999-9999', '홍길동', 1000);
INSERT INTO CUSTOMER VALUES ('010-9999-8888', '신길동', 1000);

-- 폰조회
SELECT * FROM CUSTOMER WHERE PHONE LIKE '%'||'9999' ORDER BY POINT DESC;

-- 출력
SELECT * FROM CUSTOMER ORDER BY POINT DESC;

COMMIT;
