-- 
DROP TABLE JOB;
DROP TABLE PERSON;
DROP SEQUENCE PERSON_NO_SQ;

CREATE TABLE JOB (
    JNO NUMBER(2),
    JNAME VARCHAR2(30),
    PRIMARY KEY (JNO),
    UNIQUE (JNAME) );
    
CREATE SEQUENCE PERSON_NO_SQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE PERSON (
    PNO NUMBER(5),
    PNAME VARCHAR2(30) NOT NULL,
    JNO NUMBER(2) NOT NULL,
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3),
    PRIMARY KEY (PNO),
    FOREIGN KEY (JNO) REFERENCES JOB (JNO),
    CHECK (KOR > 0 AND KOR <= 100),
    CHECK (ENG > 0 AND KOR <= 100),
    CHECK (MAT > 0 AND KOR <= 100) );

INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');

INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '설현', 20, 95, 95, 95);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '송혜교', 10, 100, 100, 100);
    
SELECT * FROM JOB;
SELECT * FROM PERSON;

-- 1번
SELECT PNO, PNAME, P.JNO, KOR, ENG, MAT FROM PERSON P, JOB J
    WHERE P.JNO = J.JNO;

INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME = '배우'), 80, 81, 88);
DELETE FROM PERSON WHERE PNAME = '홍길동';
-- 2번
SELECT ROWNUM||'등' "RANK", A.*
        FROM (SELECT PNAME||'('||PNO||'번)' "NAME", JNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOTAL" FROM PERSON P, JOB J
            WHERE P.JNO = J.JNO ORDER BY TOTAL DESC) A
    WHERE JNAME = '배우';
            
-- 3번

SELECT ROWNUM||'등' "RANK", NAME, JNAME, KOR, ENG, MAT, TOTAL 
     FROM (SELECT PNAME||'('||PNO||'번)' "NAME", JNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOTAL"
            FROM PERSON P, JOB J
            WHERE P.JNO = J.JNO ORDER BY TOTAL DESC);
    
    
COMMIT;
SELECT COUNT(*) CNT FROM JOB WHERE JNAME = '배우';
    
    
    
    
    
    
    
    
    
    