-- 테이블 삭제 및 생성
DROP SEQUENCE BOOK_SEQ;
DROP TABLE BOOK;
CREATE SEQUENCE BOOK_SEQ
    NOCACHE
    NOCYCLE;
CREATE TABLE BOOK (
    BID NUMBER(5) PRIMARY KEY, -- 책번호
    BTITLE VARCHAR2(100) NOT NULL, -- 책제목
    BPRICE NUMBER(7) NOT NULL, -- 책가격
    BIMAGE1 VARCHAR(30) NOT NULL, -- 책 대표 이미지
    BIMAGE2 VARCHAR2(30) NOT NULL, -- 책 부가 이미지
    BCONTENT VARCHAR2(4000), -- 책설명
    BDISCOUNT NUMBER(3) NOT NULL, -- 책 설명
    BRDATE DATE DEFAULT SYSDATE -- 책등록일
);
--  책 등록
INSERT INTO BOOK (BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 자바다', 30000, 'noImg.png', 'NOTHING.JPG', '책설명', 20);

-- 책 목록(전체)
SELECT * FROM BOOK ORDER BY BRDATE DESC;

-- 책목록(TOP-N구문)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) A)
    WHERE RN BETWEEN 2 AND 3;

-- 등록된 책 갯수
SELECT COUNT(*) CNT FROM BOOK;

--책 상세보기(ID로 DTO 가져오기)
SELECT * FROM BOOK WHERE BID = 1;

COMMIT;

DELETE BOOK 


