--테이블 삭제 후 생성
DROP TABLE CUSTOMER;
DROP TABLE CSM_LEVEL;
DROP SEQUENCE CUSTOMER_SQ;

CREATE TABLE CSM_LEVEL (
    LEVELNO NUMBER(1),
    LEVELNAME VARCHAR2(6) NOT NULL,
    LOW NUMBER(10),
    HIGH NUMBER(10),
    PRIMARY KEY (LEVELNO),
    CHECK (LOW >= 0),
    CHECK (HIGH >= 0) );
    
CREATE TABLE CUSTOMER (
    CID NUMBER(3),
    CTEL VARCHAR2(13) NOT NULL,
    CNAME VARCHAR(15) NOT NULL,
    CPOINT NUMBER(10) DEFAULT 1000,
    CAMOUNT NUMBER(10) DEFAULT 0,
    LEVELNO NUMBER(1) DEFAULT 0,
    PRIMARY KEY (CID),
    UNIQUE (CTEL),
    CHECK (CPOINT >= 0),
    CHECK (CAMOUNT >= 0),
    FOREIGN KEY (LEVELNO) REFERENCES CSM_LEVEL (LEVELNO) );
    
CREATE SEQUENCE CUSTOMER_SQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
    
INSERT INTO CSM_LEVEL VALUES (0, 'NORMAL', 0, 499999);  -- 0원 이상 ~ 500,000원 미만
INSERT INTO CSM_LEVEL VALUES (1, 'SILVER', 500000, 999999); -- 500,000원 이상 1,000,000원 미만
INSERT INTO CSM_LEVEL VALUES (2, 'GOLD', 1000000, 1499999);   -- 1,000,000원 이상 1,500,000원 미만
INSERT INTO CSM_LEVEL VALUES (3, 'VIP', 1500000, 1500000);    -- 1,500,000원 이상 



-- 회원가입
INSERT INTO CUSTOMER (CID, CTEL, CNAME) VALUES (CUSTOMER_SQ.NEXTVAL, '010-9999-9999', '홍길동');

INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '010-8888-9999', '신길동', 35000, 700000, 1);
INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '010-7777-9999', '김길동', 55000, 1100000, 2);
INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '010-6666-9999', '고길동', 75000, 1500000, 3);
INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '010-9999-8888', '이길동', 1000, 0, 0);

-- 아이디 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH AND CID = '1';



-- 전화번호 4자리 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP 
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH AND CTEL LIKE '%'||'010-9999-9999' ORDER BY CAMOUNT DESC;
    
-- 전화번호 전체 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP 
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH AND CTEL = '010-9999-9999';

-- 이름 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP 
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH AND CNAME = '홍길동' ORDER BY CAMOUNT DESC;

-- 포인트로 구매
UPDATE CUSTOMER SET CPOINT = CPOINT - 10000 WHERE CID = 2;

-- 물품 구매
UPDATE CUSTOMER SET CAMOUNT = CAMOUNT + 500000, CPOINT = CPOINT + (500000*0.05), 
    LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C, CSM_LEVEL L WHERE CAMOUNT+500000 BETWEEN LOW AND HIGH AND CID=1) 
    WHERE CID = 1;
-- 레벨업
UPDATE CUSTOMER SET LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C, CSM_LEVEL L
                                WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID=1) WHERE CID = 1;
        
-- 등급별 출력        
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP 
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH AND LEVELNAME = 'NORMAL' ORDER BY CAMOUNT DESC;    
    
-- 전체 출력
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO != 3) GAP 
    FROM CUSTOMER C, CSM_LEVEL CL WHERE C.LEVELNO = CL.LEVELNO
    AND CAMOUNT BETWEEN LOW AND HIGH ORDER BY CAMOUNT DESC;
    
-- 번호수정
UPDATE CUSTOMER SET CTEL = '010-8888-7777' WHERE CID = 1;

-- 회원탈퇴
DELETE FROM CUSTOMER WHERE CTEL = '010-9999-9999';

COMMIT;
ROLLBACK;
SELECT * FROM CSM_LEVEL;
SELECT * FROM CUSTOMER;

SELECT LEVELNAME FROM CSM_LEVEL;











