-- CUSTOMER DAO
-- 아이디 중복체크
SELECT * FROM CUSTOMER WHERE CID = 'ggg';

-- 회원가입
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('ggg','111','홍마동','010-1234-1234', 'g@g.com', '서울','f','1995-12-12');
    
-- 로그인
SELECT * FROM CUSTOMER WHERE CID = 'ggg' AND CPW = '111';

-- DTO가져오기
SELECT * FROM CUSTOMER WHERE CID = 'ggg';

-- 정보수정
UPDATE CUSTOMER SET CPW = '222', CNAME = '감전동', CTEL = '010-1122-2211', CEMAIL = 'gg@gg.com', CADDRESS = '강남',
    CGENDER = 'm', CBIRTH = '1999-11-11' WHERE CID = 'ggg';
    
-- 회원리스트 가져오기
SELECT * FROM (SELECT ROWNUM RN, CID, CPW, CNAME, CEMAIL, CADDRESS FROM (SELECT * FROM CUSTOMER ORDER BY CID))
    WHERE RN BETWEEN 4 AND 6;
    
-- 등록된 회원수
SELECT COUNT(*) CNT FROM CUSTOMER;

-- BOOK DAO
--  책 등록
INSERT INTO BOOK (BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 자바다', 30000, 'noImg.png', 'NOTHING.JPG', '책설명', 20);

-- 책 목록(전체)
SELECT * FROM BOOK ORDER BY BRDATE DESC;

-- 책목록(TOP-N구문)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) A)
    WHERE RN BETWEEN 2 AND 3;

-- 등록된 책 갯수
SELECT COUNT(*) CNT FROM BOOK;

--책 상세보기(ID로 DTO 가져오기)
SELECT * FROM BOOK WHERE BID = 1;

-- FILEBOARD DAO
-- 글목록
SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID = C.CID AND FNUM = '1' ORDER BY FREF DESC, FRE_STEP;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID = C.CID ORDER BY FREF DESC, FRE_STEP) A)
    WHERE RN BETWEEN 2 AND 3;


-- 글 수
SELECT COUNT(*) CNT FROM FILEBOARD;
-- 원글쓰기
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa', '제목이다', '내용이다', null, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
-- 답변글쓰기
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa', '답변이다', '답변내용이다', null, '111', 5, 1, 1, '127.0.0.1');
-- 답변글 STEP A
UPDATE FILEBOARD SET FRE_STEP = FRE_STEP + 1 WHERE FREF = 5 AND FRE_STEP > 0;
-- 글 상세보기
SELECT * FROM FILEBOARD WHERE FNUM = '1';
-- 글 수정
UPDATE FILEBOARD SET FSUBJECT = '수정된 제목', FCONTENT = '수정된 본문', FFILENAME = NULL, FPW = '111', FIP = '192.168.10.160' WHERE FNUM = 1;
-- 글 삭제
DELETE FROM FILEBOARD WHERE FNUM = 11 AND FPW = '111';
-- 조회수 올리기
UPDATE FILEBOARD SET FHIT = FHIT + 1 WHERE FNUM = 1;


COMMIT;
ROLLBACK;
SELECT * FROM FILEBOARD;
SELECT * FROM CUSTOMER;
