-- 테이블 삭제 및 생성
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
    ID VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    TEL VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50),
    ADDRESS VARCHAR2(250),
    GENDER VARCHAR2(10) NOT NULL,
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL
);
-- 회원가입
INSERT INTO CUSTOMER (ID, PW, NAME, TEL, EMAIL, ADDRESS, GENDER, BIRTH, RDATE)
    VALUES ('bbb', '111', '홍길동', '010-0000-0000', 'hong@hong.com', '서울', 'm', '1990-01-01', SYSDATE);
    
-- 로그인 / customer 불러오기
SELECT * FROM CUSTOMER WHERE ID = 'aaa';

-- 정보수정
UPDATE CUSTOMER SET PW = '222', NAME = '신길동', TEL = '02-1111-1111', EMAIL = 'sin@sin.com',
    ADDRESS = '경기', BIRTH = '1999-01-01' WHERE ID = 'aaa';
    
SELECT * FROM CUSTOMER;


COMMIT;
ROLLBACK;